# Generated by Django 2.2.6 on 2019-12-01 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('season', models.CharField(default='2019/20', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number', models.IntegerField()),
                ('height', models.IntegerField()),
                ('position', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('current', models.BooleanField(default=True)),
                ('avg_min', models.FloatField(default=0, editable=False)),
                ('avg_pts', models.FloatField(default=0, editable=False)),
                ('avg_off_reb', models.FloatField(default=0, editable=False)),
                ('avg_def_reb', models.FloatField(default=0, editable=False)),
                ('avg_tot_reb', models.FloatField(default=0, editable=False)),
                ('avg_ass', models.FloatField(default=0, editable=False)),
                ('avg_stl', models.FloatField(default=0, editable=False)),
                ('avg_blk', models.FloatField(default=0, editable=False)),
                ('avg_tos', models.FloatField(default=0, editable=False)),
                ('avg_ft', models.FloatField(default=0, editable=False)),
                ('avg_2fg', models.FloatField(default=0, editable=False)),
                ('avg_2fgm', models.FloatField(default=0, editable=False)),
                ('avg_2fga', models.FloatField(default=0, editable=False)),
                ('avg_3fgm', models.FloatField(default=0, editable=False)),
                ('avg_3fga', models.FloatField(default=0, editable=False)),
                ('avg_ftm', models.FloatField(default=0, editable=False)),
                ('avg_fta', models.FloatField(default=0, editable=False)),
                ('avg_3fg', models.FloatField(default=0, editable=False)),
                ('avg_fg', models.FloatField(default=0, editable=False)),
                ('avg_pir', models.FloatField(default=0, editable=False)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='2019/20', max_length=20)),
                ('def_rebounds', models.IntegerField()),
                ('off_rebounds', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('tos', models.IntegerField()),
                ('fg2m', models.IntegerField()),
                ('fg2a', models.IntegerField()),
                ('fg3m', models.IntegerField()),
                ('fg3a', models.IntegerField()),
                ('ftm', models.IntegerField()),
                ('fta', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamestats', to='team.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='team.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='team.Team'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('players', models.ManyToManyField(to='team.Player')),
            ],
        ),
    ]
