# Generated by Django 2.2.6 on 2019-10-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avg_2fg',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_3fg',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_ass',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_blk',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_def_reb',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_fg',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_ft',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_min',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_off_reb',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_pts',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_stl',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_tos',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_tot_reb',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
