# Generated by Django 2.2.6 on 2019-11-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20191123_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='former',
        ),
    ]
