# Generated by Django 2.2.6 on 2019-11-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20191101_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avg_2fga',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_2fgm',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_3fga',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_3fgm',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_fta',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='avg_ftm',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
