# Generated by Django 2.2.6 on 2019-11-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20191104_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avg_pir',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
